### ISSUE TITLE
basic alias seems broken ?

### ISSUE THREAD

**Issue by gedw99** [sarumaj/gh-gr#91] opened 2024-02-02 18:17 UTC
BTW thanks for this excellent extension.

```sh
# https://github.com/cli/cli/releases/tag/v2.43.1
go install github.com/cli/cli/v2/cmd/gh@v2.43.1

gh extension install sarumaj/gh-gr

gh ext list
NAME         REPO                VERSION
gh doctor    tekumara/gh-doctor  v0.0.2
gh gr        sarumaj/gh-gr       v2.6.9
gh pr-count  chaspy/gh-pr-count  v0.3.2

 gh doctor auth
✓ Authenticated to github.com as gedw99 using token with scopes admin:enterprise, admin:gpg_key, admin:org, admin:org_hook, admin:public_key, admin:repo_hook, admin:ssh_signing_key, audit_log, codespace, copilot, delete:packages, delete_repo, gist, notifications, project, repo, user, workflow, write:discussion, write:packages

 gh gr      
FATAL invalid argument           

``` 

If there are versions of the Cli your dependent on then let me know.

**Comment by sarumaj** [comment] 2024-02-03 12:34
You are welcome, @gedw99, I cannot reproduce the issue though. On which OS does this issue occur? what is the output of `cat ~/.config/gh/config.yml` (Unix gh config location)?

**Comment by sarumaj** [comment] 2024-02-09 20:32
Closing the issue, please reopen if still unsolved.

**Closed by sarumaj** 2024-02-09 20:32 UTC
